### ISSUE TITLE
Add support for MacOS notifications

### ISSUE THREAD

**Issue by dakshin-k** [kevinywlui/zlong_alert.zsh#8]
Hi, I've been using this plugin for a while now and find it very useful, however the `notify_send` package works only on Linux and not on MacOS.

I have made the required code changes on my machine and it has been working well for the past few months. So I would like to raise a PR to enable this plugin to officially support MacOS notifications.

I wanted to confirm that this is something the maintainer(s) of this project are interested in adding before going ahead with the PR. So please do let me know if I can start working on this.

Thanks a lot :)

_Note: I would be adding a dependency on the [alerter library](https://github.com/vjeantet/alerter) to accomplish this_

**Comment by dakshin-k** [comment]
Thought I would summarise the changes I plan to make in my PR so it would be easier to discuss and take a decision:

1. Update the README file with a MacOS section that tells users to install `alerter` and place it in their PATH
2. Rename the `zlong_use_notify_send` key to `zlong_send_notification` so it would apply to both `alerter` on Mac and `notify-send` on Linux - this is a breaking change so I'm open to adding a separate control variable for `alerter` instead of renaming the existing one.
3. Decide which notification command to use based on the value of `$(uname)` and modify the `zlong_alert_func()` appropriately.

**Comment by kevinywlui** [comment]
Opps. Just saw this. I'll take a look in a few days. (Locked out for a few
days from Github due to missing 2FA.)

**Comment by dakshin-k** [comment]
Hey @kevinywlui no worries, take your time

I was free over the weekend so I got started making a few changes in my [fork](https://github.com/dakshin-k/zlong_alert.zsh/tree/alerter-mac). Will raise a PR if and when you're comfortable with the changes.

**Comment by kevinywlui** [comment]
Overall the change looks good to me. I've never really used a Mac so I'll
be relying on your knowledge here. Some comments are:

1. Let's avoid breaking changes here. The variable zlong_send_notifications
name is definitely the better one but let's continue to read
the zlong_use_notify_send variable if it's set. We'll
mark zlong_use_notify_send as deprecated. If for some reason, both
variables are set, we'll have zlong_send_notifications take precedence over
zlong_use_notify_send.

2. I've been lazy with semvar but this seems worth at least a minor version
bump. I'll collect whatever we have today as the last version for 0.2.X and
let's have your change be the first 0.3.0.

I'm still locked out of my Github account and replying through emails
because I didn't notice the 2FA recovery email had a 72 hour expiration
date. But the changes look good and I think it's ready for a PR.

**Comment by dakshin-k** [comment]
Cool, I will update my fork with the changes from point 1 above and raise the PR in a couple days.

**Comment by dakshin-k** [comment]
I have raised a PR, @kevinywlui

**Comment by chrisrhayden** [comment]
closing issue as the pr was merged, thanks @dakshin-k
